eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/,http://localhost:9100/eureka/
        register-with-eureka: true
        fetch-registry: true
server:
    port: 8081
spring:
    application:
        name: order